### ISSUE TITLE
Math bugs in multiplicationnode.cpp

### ISSUE THREAD

**Issue by AaronCanciani** [psycharo/factor-graph#59]
The paper from Hans-Andrea Loeliger "An Introduction to Factor Graphs" Table 3 (where I believe you got your math expressions from) does not match your code for backward messages from a Gaussian random variable being multiplied by a matrix. See paper below for link.
 https://people.kth.se/~tjtkoski/factorgraphs.pdf

Your code on lines 70 and 71 of multiplicationnode.cpp appear incorrect to me. You are mixing up pseduo-inverses with transposes.

If you think this is incorrect please let me know because it would mean my understanding if way off, however I am fairly certain this is a bug.

**Comment by psycharo-zz** [comment]
I think you are correct, thanks for the catch!
